"""
AuditLog model.

Immutable record of every operation attempted on the platform.
Every query — successful, failed, or blocked — generates one row.

Design principles:
    1. IMMUTABLE: rows are never updated or deleted after creation
      Enforced at DB level in the migration with Postgres rules.

    2. DENORMALIZED: user_email and org_name are stored directly
      so records remain accurate even if users/orgs are deleted.

    3. COMPLETE: captures the full lifecycle of every operation —
      NL query → intent → generated SQL → execution → result.

    4. STRUCTURED: every field has a specific type and meaning,
      making it queryable for compliance and forensic investigation.

Compliance use cases:
    - "Show all DELETE operations in the last 30 days"
    - "Which user accessed the hr_salaries table last week?"
    - "How many queries were blocked by RBAC this month?"
    - "Show me every failed query for user X"

Table: audit_logs
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class AuditLog(Base):
    """
    Immutable audit record for one operation attempt.

    Created for every query regardless of outcome:
       - Successful queries
       - RBAC-blocked queries
       - Safety-layer-blocked queries
       - Failed queries (DB error, timeout)
       - Pending operations (awaiting confirmation/approval)

    Relationships:
       organization → the org this operation occurred in
    """

    __tablename__ = "audit_logs"

    # Primary key
    id: Mapped[uuid.UUID] = mapped_column(
       UUID(as_uuid=True),
       primary_key=True,
       default=uuid.uuid4,
        
    )

    # Identity — WHO performed this operation
    #
    # Denormalized: we store the actual email and org name,
    # not just the IDs. If the user account is deleted later,
    # this record still shows who did it.
    user_id: Mapped[uuid.UUID | None] = mapped_column(
       UUID(as_uuid=True),
       nullable=True,
       index=True,
       comment=(
           "FK to users table. NULL if user was deleted after the operation. "
           "Always check user_email for the authoritative identity."
       ),
    )

    user_email: Mapped[str] = mapped_column(
       String(255),
       nullable=False,
       index=True,
       comment=(
           "DENORMALIZED: email at time of operation. "
           "Preserved even if user account is later deleted."
       ),
    )

    user_role: Mapped[str] = mapped_column(
       String(50),
       nullable=False,
       comment=(
           "DENORMALIZED: role at time of operation. "
           "e.g. 'dba', 'analyst'. "
           "Preserved even if role assignment changes later."
       ),
    )

    org_id: Mapped[uuid.UUID | None] = mapped_column(
       UUID(as_uuid=True),
       ForeignKey("organizations.id", ondelete="SET NULL"),
       nullable=True,
       index=True,
       comment="FK to organizations. SET NULL if org is deleted.",
    )

    org_name: Mapped[str] = mapped_column(
       String(255),
       nullable=False,
       comment=(
           "DENORMALIZED: organization name at time of operation. "
           "Preserved even if organization is later renamed or deleted."
       ),
    )

    # Request tracing
    #
    # session_id: groups all queries in one user session
    # request_id: unique ID for this specific API request
    # Both are useful for correlating logs across services.
    session_id: Mapped[uuid.UUID | None] = mapped_column(
       UUID(as_uuid=True),
       nullable=True,
       index=True,
       comment="Groups all queries within one user login session.",
    )

    request_id: Mapped[uuid.UUID] = mapped_column(
       UUID(as_uuid=True),
       nullable=False,
       default=uuid.uuid4,
       comment="Unique ID for this specific API request. Use for log correlation.",
    )

    # Operation — WHAT was attempted
    natural_language_query: Mapped[str | None] = mapped_column(
       Text,
       nullable=True,
       comment="The exact text the user submitted.",
    )

    intent_classification: Mapped[str | None] = mapped_column(
       String(50),
       nullable=True,
       comment=(
           "What the LLM classified this query as. "
           "One of: READ, INSERT, UPDATE, DELETE, DDL"
       ),
    )

    generated_sql: Mapped[str | None] = mapped_column(
       Text,
       nullable=True,
       comment=(
           "The SQL generated by the LLM. "
           "NULL if query was blocked before SQL generation."
       ),
    )

    sql_operation: Mapped[str | None] = mapped_column(
       String(50),
       nullable=True,
       comment=(
           "Actual SQL operation detected by sqlglot parser. "
           "May differ from intent_classification if LLM hallucinated "
           "a different operation type — this mismatch triggers a block."
       ),
    )

    # Target — WHERE the operation ran
    connection_id: Mapped[uuid.UUID | None] = mapped_column(
       UUID(as_uuid=True),
       nullable=True,
       comment="Primary database connection used.",
    )

    connection_name: Mapped[str | None] = mapped_column(
       String(255),
       nullable=True,
       comment="DENORMALIZED: connection name at time of operation.",
    )

    target_tables: Mapped[list[str] | None] = mapped_column(
       ARRAY(String),
       nullable=True,
       comment=(
           "Array of table names touched by this query. "
           "e.g. ['orders', 'customers']. "
           "Extracted by sqlglot from the generated SQL."
       ),
    )

    is_federated: Mapped[bool] = mapped_column(
       Boolean,
       default=False,
       nullable=False,
       comment="True if this query spanned multiple databases.",
    )

    # Result — WHAT HAPPENED
    status: Mapped[str] = mapped_column(
       String(50),
       nullable=False,
       index=True,
       comment=(
           "Final outcome of this operation. One of: "
           "success, blocked, failed, "
           "pending_confirmation, pending_approval"
       ),
    )

    block_reason: Mapped[str | None] = mapped_column(
       String(100),
       nullable=True,
       comment=(
           "Why this operation was blocked. "
           "One of: rbac_denied, safety_blocked, "
           "injection_detected, permission_denied, "
           "table_grant_denied. NULL if not blocked."
       ),
    )

    affected_rows: Mapped[int | None] = mapped_column(
       Integer,
       nullable=True,
       comment=(
           "Number of rows affected by INSERT/UPDATE/DELETE. "
           "NULL for SELECT queries or blocked operations."
       ),
    )

    result_row_count: Mapped[int | None] = mapped_column(
       Integer,
       nullable=True,
       comment="Number of rows returned by SELECT queries.",
    )

    execution_time_ms: Mapped[int | None] = mapped_column(
       Integer,
       nullable=True,
       comment="Total time from query receipt to result delivery in milliseconds.",
    )

    error_message: Mapped[str | None] = mapped_column(
       Text,
       nullable=True,
       comment="Error details if status=failed.",
    )

    # Safety signals
    injection_detected: Mapped[bool] = mapped_column(
       Boolean,
       default=False,
       nullable=False,
       comment="True if SQL injection pattern was detected in this query.",
    )

    was_self_corrected: Mapped[bool] = mapped_column(
       Boolean,
       default=False,
       nullable=False,
       comment="True if the SQL generator needed self-correction retries.",
    )

    correction_attempts: Mapped[int] = mapped_column(
       Integer,
       default=0,
       nullable=False,
       comment="How many self-correction attempts were made (0-3).",
    )

    # Timestamps
    requested_at: Mapped[datetime] = mapped_column(
       DateTime(timezone=True),
       default=utcnow,
       nullable=False,
       index=True,
       comment="When the API received this request.",
    )

    executed_at: Mapped[datetime | None] = mapped_column(
       DateTime(timezone=True),
       nullable=True,
       comment=(
           "When SQL execution completed. "
           "NULL if blocked before execution."
       ),
    )

    # Relationships
    organization: Mapped["Organization"] = relationship(
       "Organization",
       back_populates="audit_logs",
    )

    def __repr__(self) -> str:
       return (
           f"<AuditLog "
           f"id={self.id} "
           f"user={self.user_email} "
           f"status={self.status} "
           f"op={self.sql_operation}>"
       )