"""
PendingOperation model.

Stores dangerous operations that require confirmation or approval
before execution. Part of the SQL Safety Layer.

Workflow:
    1. User submits NL query that maps to a dangerous operation
      (bulk DELETE, DROP, bulk UPDATE, ALTER)
    2. Permission engine detects requires_gate=True
    3. System creates PendingOperation with status='pending'
    4. System returns 202 with pending_operation_id + confirmation_token
    5a. CONFIRMATION gate: user re-submits with confirmation_token
    5b. APPROVAL gate: org_admin calls POST /pending/{id}/approve
    6. System executes the SQL and updates status='executed'

Expiry:
    Operations expire after 30 minutes (expires_at).
    Expired operations cannot be approved or confirmed.
    A Celery task sweeps and marks expired operations hourly.

Table: pending_operations
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class PendingOperation(Base):
    """
    A dangerous SQL operation awaiting confirmation or approval.

    Relationships:
       organization → the org this operation belongs to
    """

    __tablename__ = "pending_operations"

    # Primary key
    id: Mapped[uuid.UUID] = mapped_column(
       UUID(as_uuid=True),
       primary_key=True,
       default=uuid.uuid4,
        
    )

    # Ownership
    user_id: Mapped[uuid.UUID] = mapped_column(
       UUID(as_uuid=True),
       nullable=False,
       index=True,
       comment="User who submitted the original query.",
    )

    org_id: Mapped[uuid.UUID] = mapped_column(
       UUID(as_uuid=True),
       ForeignKey("organizations.id", ondelete="CASCADE"),
       nullable=False,
       index=True,
       comment="Organization context for this operation.",
    )

    # Operation details
    operation_type: Mapped[str] = mapped_column(
       String(50),
       nullable=False,
       comment=(
           "SQL operation type. "
           "One of: DELETE, UPDATE, DROP, TRUNCATE, ALTER"
       ),
    )

    natural_language_query: Mapped[str] = mapped_column(
       Text,
       nullable=False,
       comment="The original NL query submitted by the user.",
    )

    generated_sql: Mapped[str] = mapped_column(
       Text,
       nullable=False,
       comment=(
           "The validated SQL that will execute upon approval. "
           "This is frozen at creation time — "
           "the exact SQL that gets executed, nothing else."
       ),
    )

    connection_id: Mapped[uuid.UUID | None] = mapped_column(
       UUID(as_uuid=True),
       nullable=True,
       comment="Target database connection for this operation.",
    )

    # Impact preview
    #
    # Shown to the user before they confirm.
    # Generated by running EXPLAIN on the SQL before storing.
    estimated_affected_rows: Mapped[int | None] = mapped_column(
       Integer,
       nullable=True,
       comment=(
           "Estimated rows affected by this operation. "
           "From EXPLAIN output. Shown to user before confirmation."
       ),
    )

    # Gate type
    gate_type: Mapped[str] = mapped_column(
       String(50),
       nullable=False,
       comment=(
           "Type of gate required. "
           "confirmation: user re-submits with token. "
           "approval: org_admin must approve via API."
       ),
    )

    # Status lifecycle
    #
    # pending    → waiting for confirmation or approval
    # approved   → org_admin approved (approval gate only)
    # rejected   → org_admin rejected
    # executed   → SQL was executed successfully
    # expired    → expires_at passed before confirmation/approval
    # cancelled  → user cancelled the operation
    status: Mapped[str] = mapped_column(
       String(50),
       default="pending",
       nullable=False,
       index=True,
       comment="Current status of this pending operation.",
    )

    # Confirmation token
    #
    # A short-lived token sent to the user with the 202 response.
    # The user must include this token when re-submitting to confirm.
    # This proves the confirmation is intentional, not a replay attack.
    confirmation_token: Mapped[str | None] = mapped_column(
       String(255),
       nullable=True,
       unique=True,
       comment=(
           "One-time token required for user self-confirmation. "
           "NULL for approval-gate operations. "
           "Invalidated after use."
       ),
    )

    # Approval fields (for approval gate only)
    approved_by: Mapped[uuid.UUID | None] = mapped_column(
       UUID(as_uuid=True),
       nullable=True,
       comment="org_admin who approved this operation. NULL until approved.",
    )

    approval_notes: Mapped[str | None] = mapped_column(
       Text,
       nullable=True,
       comment="Optional note from the approving admin.",
    )

    # Timestamps
    expires_at: Mapped[datetime] = mapped_column(
       DateTime(timezone=True),
       nullable=False,
       comment=(
           "When this pending operation expires. "
           "Default: 30 minutes after creation. "
           "Expired operations cannot be confirmed or approved."
       ),
    )

    created_at: Mapped[datetime] = mapped_column(
       DateTime(timezone=True),
       default=utcnow,
       nullable=False,
    )

    resolved_at: Mapped[datetime | None] = mapped_column(
       DateTime(timezone=True),
       nullable=True,
       comment=(
           "When this operation was resolved "
           "(executed, rejected, expired, or cancelled)."
       ),
    )

    # Relationships
    organization: Mapped["Organization"] = relationship(
       "Organization",
       back_populates="pending_operations",
    )

    def __repr__(self) -> str:
       return (
           f"<PendingOperation "
           f"id={self.id} "
           f"type={self.operation_type} "
           f"status={self.status} "
           f"gate={self.gate_type}>"
       )