"""initial_schema

Revision ID: c774493cb199
Revises: 
Create Date: 2026-07-16 11:46:43.546630+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c774493cb199'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='Organization that owns this database connection.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who registered this connection. NULL if user was deleted.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Human-readable label for this connection. e.g. 'Production Sales DB', 'Analytics Warehouse'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of what data this database contains.'),
    sa.Column('db_type', sa.String(length=50), nullable=False, comment='Database engine type. One of: postgres, mysql, bigquery, snowflake'),
    sa.Column('host', sa.String(length=500), nullable=True, comment='Database server hostname or IP address.'),
    sa.Column('port', sa.Integer(), nullable=True, comment='Database server port. e.g. 5432 for Postgres, 3306 for MySQL'),
    sa.Column('database_name', sa.String(length=255), nullable=True, comment='Name of the specific database/schema to connect to.'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Database username for authentication.'),
    sa.Column('encrypted_password', sa.Text(), nullable=True, comment='AES-256-GCM encrypted database password. Base64-encoded ciphertext. Never store plaintext here.'),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Database-type-specific connection parameters as JSON.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Inactive connections cannot be queried.'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='True if the connection has been successfully tested. Set to True after POST /connections/{id}/test succeeds.'),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True, comment='When schema was last crawled and embedded into Pinecone. NULL means this connection has never been crawled.'),
    sa.Column('crawl_status', sa.String(length=50), nullable=True, comment='Current crawl state. One of: pending, crawling, completed, failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_connections_db_type'), 'database_connections', ['db_type'], unique=False)
    op.create_index(op.f('ix_database_connections_org_id'), 'database_connections', ['org_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Display name of the organization. e.g. 'Acme Corp'"),
    sa.Column('slug', sa.String(length=100), nullable=False, comment="URL-safe unique identifier. e.g. 'acme-corp'. Used in API paths and for quick lookups."),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the organization.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Inactive organizations cannot perform queries. Use this to suspend an org without deleting its data.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False, comment='The action being permitted. One of: SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, TRUNCATE, EXPORT, MANAGE, VIEW'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='What the operation applies to. One of: table, connection, organization, audit_log, user'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable explanation of what this permission allows.'),
    sa.Column('requires_gate', sa.Boolean(), nullable=False, comment='If True, this operation cannot execute immediately. User must confirm or an admin must approve first.'),
    sa.Column('gate_type', sa.String(length=50), nullable=True, comment='Type of gate required when requires_gate=True. One of: confirmation, approval. NULL when requires_gate=False.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Machine-readable role identifier. One of: super_admin, org_admin, dba, analyst, viewer. Used in permission checks throughout the codebase.'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment="Human-readable name shown in the UI. e.g. 'Database Administrator'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Explains what this role can and cannot do.'),
    sa.Column('is_system_role', sa.Boolean(), nullable=False, comment='If True, this role cannot be deleted. All five platform roles are system roles.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Primary login identifier. Must be unique across platform.'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment="bcrypt hash of the user's password. Never store plaintext."),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Display name shown in the UI.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Inactive users cannot log in. Use this instead of deleting accounts.'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Email verification status. Reserved for future email verification flow.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When this account was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='When this account was last modified.'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='When this user last successfully authenticated.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='FK to users table. NULL if user was deleted after the operation. Always check user_email for the authoritative identity.'),
    sa.Column('user_email', sa.String(length=255), nullable=False, comment='DENORMALIZED: email at time of operation. Preserved even if user account is later deleted.'),
    sa.Column('user_role', sa.String(length=50), nullable=False, comment="DENORMALIZED: role at time of operation. e.g. 'dba', 'analyst'. Preserved even if role assignment changes later."),
    sa.Column('org_id', sa.UUID(), nullable=True, comment='FK to organizations. SET NULL if org is deleted.'),
    sa.Column('org_name', sa.String(length=255), nullable=False, comment='DENORMALIZED: organization name at time of operation. Preserved even if organization is later renamed or deleted.'),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Groups all queries within one user login session.'),
    sa.Column('request_id', sa.UUID(), nullable=False, comment='Unique ID for this specific API request. Use for log correlation.'),
    sa.Column('natural_language_query', sa.Text(), nullable=True, comment='The exact text the user submitted.'),
    sa.Column('intent_classification', sa.String(length=50), nullable=True, comment='What the LLM classified this query as. One of: READ, INSERT, UPDATE, DELETE, DDL'),
    sa.Column('generated_sql', sa.Text(), nullable=True, comment='The SQL generated by the LLM. NULL if query was blocked before SQL generation.'),
    sa.Column('sql_operation', sa.String(length=50), nullable=True, comment='Actual SQL operation detected by sqlglot parser. May differ from intent_classification if LLM hallucinated a different operation type — this mismatch triggers a block.'),
    sa.Column('connection_id', sa.UUID(), nullable=True, comment='Primary database connection used.'),
    sa.Column('connection_name', sa.String(length=255), nullable=True, comment='DENORMALIZED: connection name at time of operation.'),
    sa.Column('target_tables', postgresql.ARRAY(sa.String()), nullable=True, comment="Array of table names touched by this query. e.g. ['orders', 'customers']. Extracted by sqlglot from the generated SQL."),
    sa.Column('is_federated', sa.Boolean(), nullable=False, comment='True if this query spanned multiple databases.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Final outcome of this operation. One of: success, blocked, failed, pending_confirmation, pending_approval'),
    sa.Column('block_reason', sa.String(length=100), nullable=True, comment='Why this operation was blocked. One of: rbac_denied, safety_blocked, injection_detected, permission_denied, table_grant_denied. NULL if not blocked.'),
    sa.Column('affected_rows', sa.Integer(), nullable=True, comment='Number of rows affected by INSERT/UPDATE/DELETE. NULL for SELECT queries or blocked operations.'),
    sa.Column('result_row_count', sa.Integer(), nullable=True, comment='Number of rows returned by SELECT queries.'),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True, comment='Total time from query receipt to result delivery in milliseconds.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details if status=failed.'),
    sa.Column('injection_detected', sa.Boolean(), nullable=False, comment='True if SQL injection pattern was detected in this query.'),
    sa.Column('was_self_corrected', sa.Boolean(), nullable=False, comment='True if the SQL generator needed self-correction retries.'),
    sa.Column('correction_attempts', sa.Integer(), nullable=False, comment='How many self-correction attempts were made (0-3).'),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False, comment='When the API received this request.'),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True, comment='When SQL execution completed. NULL if blocked before execution.'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_requested_at'), 'audit_logs', ['requested_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_email'), 'audit_logs', ['user_email'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='The user who is a member of this organization.'),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='The organization this user belongs to.'),
    sa.Column('role_id', sa.UUID(), nullable=False, comment='The role assigned to this user within this organization. RESTRICT prevents deleting a role that is in use.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Inactive members cannot perform operations in this org. Use this to suspend access without removing membership history.'),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False, comment='When this user was added to the organization.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='When this membership was last modified (e.g. role changed).'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_org_member_user_org')
    )
    op.create_index(op.f('ix_organization_members_org_id'), 'organization_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('pending_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who submitted the original query.'),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='Organization context for this operation.'),
    sa.Column('operation_type', sa.String(length=50), nullable=False, comment='SQL operation type. One of: DELETE, UPDATE, DROP, TRUNCATE, ALTER'),
    sa.Column('natural_language_query', sa.Text(), nullable=False, comment='The original NL query submitted by the user.'),
    sa.Column('generated_sql', sa.Text(), nullable=False, comment='The validated SQL that will execute upon approval. This is frozen at creation time — the exact SQL that gets executed, nothing else.'),
    sa.Column('connection_id', sa.UUID(), nullable=True, comment='Target database connection for this operation.'),
    sa.Column('estimated_affected_rows', sa.Integer(), nullable=True, comment='Estimated rows affected by this operation. From EXPLAIN output. Shown to user before confirmation.'),
    sa.Column('gate_type', sa.String(length=50), nullable=False, comment='Type of gate required. confirmation: user re-submits with token. approval: org_admin must approve via API.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Current status of this pending operation.'),
    sa.Column('confirmation_token', sa.String(length=255), nullable=True, comment='One-time token required for user self-confirmation. NULL for approval-gate operations. Invalidated after use.'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='org_admin who approved this operation. NULL until approved.'),
    sa.Column('approval_notes', sa.Text(), nullable=True, comment='Optional note from the approving admin.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When this pending operation expires. Default: 30 minutes after creation. Expired operations cannot be confirmed or approved.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='When this operation was resolved (executed, rejected, expired, or cancelled).'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_token')
    )
    op.create_index(op.f('ix_pending_operations_org_id'), 'pending_operations', ['org_id'], unique=False)
    op.create_index(op.f('ix_pending_operations_status'), 'pending_operations', ['status'], unique=False)
    op.create_index(op.f('ix_pending_operations_user_id'), 'pending_operations', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User this token belongs to. CASCADE: deleting a user deletes all their tokens.'),
    sa.Column('token_hash', sa.String(length=500), nullable=False, comment='bcrypt hash of the refresh token. Compare with bcrypt.verify(incoming_token, token_hash). Never store the raw token value.'),
    sa.Column('device_info', sa.Text(), nullable=True, comment="Human-readable device description from User-Agent header. e.g. 'Chrome on Windows', 'Safari on iPhone'. Shown in the 'Active Sessions' UI."),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address when this token was issued. IPv4 max 15 chars, IPv6 max 45 chars. Used for suspicious activity detection.'),
    sa.Column('is_revoked', sa.Boolean(), nullable=False, comment='True if this token has been explicitly revoked. Revoked tokens are rejected even before expiry. We keep the row for audit purposes.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When this token expires. Default: 7 days after creation. Expired tokens are rejected regardless of is_revoked.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When this token was issued (user logged in).'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='When this token was last used to get a new access token. Updated on every successful token refresh. Used to detect inactive sessions.'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='When this token was revoked. NULL if still active.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False, comment='The role being granted this permission.'),
    sa.Column('permission_id', sa.UUID(), nullable=False, comment='The permission being granted to this role.'),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False, comment='When this permission was granted to this role.'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('schema_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False, comment='The database connection this schema belongs to.'),
    sa.Column('table_name', sa.String(length=255), nullable=False, comment='Name of the table this column belongs to.'),
    sa.Column('table_schema', sa.String(length=255), nullable=True, comment="Database schema/namespace. e.g. 'public' in Postgres, 'dbo' in SQL Server. NULL for databases without schemas."),
    sa.Column('column_name', sa.String(length=255), nullable=False, comment='Name of the column.'),
    sa.Column('data_type', sa.String(length=100), nullable=True, comment="Column data type as reported by the source database. e.g. 'integer', 'character varying', 'timestamp with time zone'"),
    sa.Column('is_nullable', sa.Boolean(), nullable=False, comment='True if this column allows NULL values.'),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False, comment='True if this column is part of the primary key. Helps the SQL generator write correct JOIN conditions.'),
    sa.Column('is_foreign_key', sa.Boolean(), nullable=False, comment='True if this column references another table.'),
    sa.Column('fk_references', sa.String(length=500), nullable=True, comment="What this foreign key references. Format: 'referenced_table.referenced_column' e.g. 'customers.id'. NULL if is_foreign_key=False."),
    sa.Column('pinecone_vector_id', sa.String(length=500), nullable=True, comment="ID of this column's vector in Pinecone. Set after embedding during schema crawl. NULL means this column has not been embedded yet."),
    sa.Column('embedded_text', sa.Text(), nullable=True, comment="The text string that was sent to the embedding model. e.g. 'orders table, customer_id column, integer, foreign key to customers.id'"),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=False, comment='When this schema metadata was discovered.'),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_snapshots_connection_id'), 'schema_snapshots', ['connection_id'], unique=False)
    op.create_index(op.f('ix_schema_snapshots_table_name'), 'schema_snapshots', ['table_name'], unique=False)
    op.create_table('table_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='The user this grant applies to.'),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='Organization context for this grant.'),
    sa.Column('connection_id', sa.UUID(), nullable=False, comment='The database connection containing the target table.'),
    sa.Column('table_name', sa.String(length=255), nullable=False, comment="The specific table this grant applies to. Use '*' to apply to all tables in the connection."),
    sa.Column('operation', sa.String(length=50), nullable=False, comment='The SQL operation this grant covers. One of: SELECT, INSERT, UPDATE, DELETE, EXPORT'),
    sa.Column('is_granted', sa.Boolean(), nullable=False, comment='True = explicitly allowed. False = explicitly denied. Explicit deny overrides role-level permissions.'),
    sa.Column('granted_by', sa.UUID(), nullable=True, comment='User (org_admin or super_admin) who created this grant.'),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False, comment='When this grant was created.'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='When this grant was revoked. NULL means still active. We keep the row for audit history — setting is_granted=False is the revocation.'),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_grants_connection_id'), 'table_grants', ['connection_id'], unique=False)
    op.create_index(op.f('ix_table_grants_org_id'), 'table_grants', ['org_id'], unique=False)
    op.create_index(op.f('ix_table_grants_user_id'), 'table_grants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_grants_user_id'), table_name='table_grants')
    op.drop_index(op.f('ix_table_grants_org_id'), table_name='table_grants')
    op.drop_index(op.f('ix_table_grants_connection_id'), table_name='table_grants')
    op.drop_table('table_grants')
    op.drop_index(op.f('ix_schema_snapshots_table_name'), table_name='schema_snapshots')
    op.drop_index(op.f('ix_schema_snapshots_connection_id'), table_name='schema_snapshots')
    op.drop_table('schema_snapshots')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_pending_operations_user_id'), table_name='pending_operations')
    op.drop_index(op.f('ix_pending_operations_status'), table_name='pending_operations')
    op.drop_index(op.f('ix_pending_operations_org_id'), table_name='pending_operations')
    op.drop_table('pending_operations')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_org_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_email'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_requested_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_database_connections_org_id'), table_name='database_connections')
    op.drop_index(op.f('ix_database_connections_db_type'), table_name='database_connections')
    op.drop_table('database_connections')
    # ### end Alembic commands ###